# Generated by Django 3.2.5 on 2021-07-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timmyBlog', '0002_auto_20210730_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
